language: go
sudo: true
go:
  - "1.10"
install:
  - go get github.com/namsral/flag
  - go get github.com/op/go-logging
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t brokken/traefik-forward-auth
